backend:
site_url: https://peaceforpeopleofficial.netlify.app
  name: github
  repo: PeaceForPeopleOFfficial/peacetube-
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "শান্তির বাণী (Articles)"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "শিরোনাম (Title)", name: "title", widget: "string"}
      - {label: "তারিখ (Publish Date)", name: "date", widget: "datetime"}
      - {label: "শান্তির বাণী / মূল লেখা (Body)", name: "body", widget: "markdown"}
