name: Deploy Static Content to Vercel

on:
  push:
    branches:
      - main  # অথবা আপনার ডিফল্ট ব্রাঞ্চের নাম যদি master হয় তবে master লিখবেন

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Vercel Deployment
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
